= BeanBand Backlog

== Focus Areas

We are currently putting all our efforts into improving the musical quality of
the generated playbacks. To that end we need we are looking for new as well as
improvements and enhancements to existing +Arranger+ and +Band+
implementations. In addition we are looking for high-quality and
well-documented Song Files to enrich our test portfolio.

== Cleaning Up

In addition to the official Backlog we use +TODO+ and +FIXME+ annotations
directly in the Java code to mark all areas where immediate work is required.

Also the code should be kept free of any warnings and in general as clean as
possible.

== Backlog

* Create new basic Arrangers
 ** Create +PianoVoicingArranger+ that calculates one or more piano voicings.
 ** Create +ScaleArranger+ (and +ScaleAnnotation+) that calculates (octave-independent) scales, bass- and root-notes, lead notes, function notes etc.
 ** Refactor +BassLineArranger+ and +VoicingArranger+ to utilize the output of the +ScaleArranger+
 ** Enhance +BassLineArranger+ to include more than the bass note (fifth, fourth, lead tones, walking lines)
 ** Enhance +FormArranger+ to actually detect formal features of the leadsheet, like intros, chorusses, bridges, breaks, etc. 
* Enhance BasicFourBeatBand to form a full showcase/reference implementation
 ** Create BasicFourBeatPianoMusician
 ** Clean up and improve existing Musicians
 ** Support four changes per bar
 ** Continuously improve existing Arrangers and Musicians
* Add new Bands

